version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "4545:4545"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:4545"

  db:
    image: postgres:10-alpine